language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

notifications:
  email:
    - travis@23-5.eu

install: "pip install -r server/Pip-packages.txt"

# command to run tests
script: nosetests
