language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

notifications:
  email:
    recipients:
      - travis@23-5.eu
    on_success: always
    on_failure: always
  irc: "chat.freenode.net#radioaldebaran"

install: "pip install -r server/Pip-packages.txt"

# command to run tests
script: nosetests
